services:
  client:
    image: thoomaas123/sc-planner-client:${CLIENT_TAG:-latest}
    ports:
      - '3001:80'
    env_file:
      - ./.env
    depends_on:
      - server
    pull_policy: always
    networks:
      - sc-planner-network

  server:
    image: thoomaas123/sc-planner-server:${SERVER_TAG:-latest}
    ports:
      - '3002:3001'
    env_file:
      - ./.env
    pull_policy: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
    networks:
      - sc-planner-network
    labels:
      - maintainer=ThomasFourties
  database:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - sc_planner_db_data:/var/lib/postgresql/data
    networks:
      - sc-planner-network

volumes:
  sc_planner_db_data:

networks:
  sc-planner-network:
    driver: bridge
