services:
  client:
    image: thoomaas123/sc-planner-client:${CLIENT_TAG}
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - API_URL=http://server:3002/api
    depends_on:
      - server
    pull_policy: always
    networks:
      - sc-planner-network

  server:
    image: thoomaas123/sc-planner-server:${SERVER_TAG}
    ports:
      - '3001:3002'
    env_file:
      - ./.env
    pull_policy: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
    networks:
      - sc-planner-network

  database:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - _database:/var/lib/postgresql/data
    networks:
      - sc-planner-network

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: 'pappu687'
    depends_on:
      - database
    networks:
      - sc-planner-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-staging
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/prometheus-staging.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://staging.sc-planner.thomasfourties.fr/prometheus/'
      - '--web.route-prefix=/'
    networks:
      - sc-planner-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-staging
    ports:
      - '3003:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://staging.sc-planner.thomasfourties.fr/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - sc-planner-network
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-staging
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    networks:
      - sc-planner-network

volumes:
  _database:
  prometheus_data:
  grafana_data:

networks:
  sc-planner-network:
    driver: bridge
