services:
  client:
    image: thoomaas123/sc-planner-client
    ports:
      - '3001:80'
    env_file:
      - ./.env
    depends_on:
      - server
    pull_policy: always

  server:
    image: thoomaas123/sc-planner-server
    ports:
      - '3002:3001'
    env_file:
      - ./.env
    pull_policy: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
    labels:
      - maintainer=ThomasFourties
  database:
    image: postgres:13
    ports:
      - '5433:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - sc_planner_db_data:/var/lib/postgresql/data

volumes:
  sc_planner_db_data:
