services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: sc-planner/client
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    command: sh -c "rm -rf .nuxt .output && pnpm run dev"
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    image: sc-planner/server
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - sc_planner_db_data:/var/lib/postgresql/data

volumes:
  sc_planner_db_data:
  client_node_modules:
  server_node_modules:
