services:
  client:
    image: thoomaas123/sc-planner-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    env_file:
      - ./.env
    command: npm run dev
    depends_on:
      - server

  server:
    image: thoomaas123/sc-planner-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '3002:3001'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    command: npm run start:dev