services:
  client:
    image: thoomaas123/sc-planner-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: npm run dev
    depends_on:
      - server

  server:
    image: thoomaas123/sc-planner-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    command: npm run start:dev
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - '5433:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
