services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: sc-planner/client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env.dev
    command: npm run dev
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    image: sc-planner/server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    env_file:
      - ./.env.dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    command: npm run start:dev
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
