apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: scplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: ${DATABASE_NAME}
        - name: POSTGRES_USER
          value: ${DATABASE_USER}
        - name: POSTGRES_PASSWORD
          value: ${DATABASE_PASSWORD}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: scplanner
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP