apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: sc-planner
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: node:18-alpine
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: SERVICE_NAME
          value: "auth-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sc-planner
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 