apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: sc-planner
  labels:
    app: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
      - name: monitoring-service
        image: node:18-alpine
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: SERVICE_NAME
          value: "monitoring-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: sc-planner
spec:
  selector:
    app: monitoring-service
  ports:
  - port: 3006
    targetPort: 3006
  type: ClusterIP 