apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: sc-planner
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: node:18-alpine
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: SERVICE_NAME
          value: "task-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: sc-planner
spec:
  selector:
    app: task-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP 