apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: sc-planner
  labels:
    app: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: node:18-alpine
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: SERVICE_NAME
          value: "client-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: sc-planner
spec:
  selector:
    app: client-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP 