apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: sc-planner
  labels:
    app: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
      - name: project-service
        image: node:18-alpine
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: SERVICE_NAME
          value: "project-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: sc-planner
spec:
  selector:
    app: project-service
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP 