name: Docker Build and Push

on:
  push:
    branches:
      - prod
    paths:
      - 'client/**'  # Surveille les changements dans le dossier client (frontend)
      - 'server/**'  # Surveille les changements dans le dossier server (backend)

jobs:
  frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-22.04
    if: ${{ github.event.head_commit.modified != null && contains(github.event.head_commit.modified, 'client') }}  # Exécute si 'client' a changé
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: thoomaas123/sc-planner-client

  backend:
    name: Build and Push Backend
    runs-on: ubuntu-22.04
    if: ${{ github.event.head_commit.modified != null && contains(github.event.head_commit.modified, 'server') }}  # Exécute si 'server' a changé
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: thoomaas123/sc-planner-server